services:
  app:
    build: .
    container_name: native-app
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-native.entrypoints=websecure
      - traefik.http.routers.app-native.rule=Host(`veyvy.space`)
      - traefik.http.routers.app-native.tls.certresolver=letsencryptresolver
      - traefik.http.routers.app-native.service=app-streaming_svc
      - traefik.http.services.app-native_svc.loadbalancer.server.port=3000
      - traefik.docker.network=web

networks:
  web:
    external: true
